module.exports = {
    "ER1001": "ER1001 - Partner steamId is required to fetch partner inventory.",
    "ER1002": "ER1002 - Unable to load user inventory. SubError: %s.",
    "ER1003": "ER1003 - Invalid input data supplied for deposit command.",
    "ER1004": "ER1004 - Partner's trade url token would be required for offer sending.",
    "ER1005": "ER1005 - Items to receive is not set.",
    "ER1006": "ER1006 - Deposit command must not have items_to_give set.",
    "ER1007": "ER1007 - Error getting user details. SubError: %s.",
    "ER1008": "ER1008 - Escrow hold applicable on trade. Bot escrow days: %s, Your escrow days: %s.",
    "ER1009": "ER1009 - Some of the input items params missing.",
    "ER1010": "ER1010 - Item with market hash name '%s' and asset id '%s' is not present in your inventory. ",
    "ER1011": "ER1011 - Unable to send deposit offer (offer id: '%s'). SubError: %s.",
    "ER1012": "ER1012 - Unable to load own inventory. SubError: %s.",
    "ER1013": "ER1013 - Invalid input data supplied for withdraw command.",
    "ER1014": "ER1014 - Partner's trade url token would be required for offer sending.",
    "ER1015": "ER1015 - Items to give is not set.",
    "ER1016": "ER1016 - Withdraw command must not have items_to_receive set.",
    "ER1017": "ER1017 - Some of the items are not available.",
    "ER1018": "ER1018 - Item with market hash name '%s' and asset id '%s' is not present in the bot inventory.",
    "ER1019": "ER1019 - Unable to send withdrawal offer (offer id: '%s'). SubError: %s.",
    "ER1020": "ER1020 - Unable to fetch the new asset IDs of items for trade offer '%s'. Attempt #: %s.",
    "ER1021": "ER1021 - Deposit offer '%s' have no valid offer state.",
    "ER1022": "ER1022 - Withdraw offer '%s' have no valid offer state.",
    "ER1023": "ER1023 - Offer '%s' do not have valie type.",
    "ER1024": "ER1024 - User with SteamId '%s' has sent new offer '%s' directly.",
    "ER1025": "ER1025 - Unable to process accepted deposit offer '%s'. Something bad happening at Steam's side. Please contact support.",
    "ER1026": "ER1026 - Deposit offer '%s' was %s.",
    "ER1027": "ER1027 - Deposit offer '%s' have state %s.",
    "ER1028": "ER1028 - Withdrawal offer '%s' was %s.",
    "ER1029": "ER1029 - Withdrawal offer '%s' have state %s.",
    "ER1030": "ER1030 - Bot options must have following fields: 'id', 'account', 'password', 'shared_secret' and 'identity_secret'.",
    "ER1031": "ER1031 - BOT[%s] ERROR => %s.",
    "ER1032": "ER1032 - Command data format is invalid no data or command set.",
    "ER1033": "ER1033 - Unknown command supplied.",

    //DATABASE ERRORS
    "DB-ER1001": "DB-ER1001 - Deposit outgoing offer save error. SubError: %s.",
    "DB-ER1002": "DB-ER1002 - Unable to update items state to WithdrawalAwaiting for withdrawal offer (offer id: '%s'). SubError: %s.",
    "DB-ER1003": "DB-ER1003 - Unable to update items state to WithdrawalAwaiting for withdrawal offer (offer id: '%s'). SubError: %s.",
    "DB-ER1004": "DB-ER1004 - Unable to get user items for withdrawal offer (offer id: '%s'). SubError: %s.",
    "DB-ER1005": "DB-ER1005 - Deposit offer '%s' accepted but offer saving failed. SubError: %s.",
    "DB-ER1006": "DB-ER1006 - Deposit offer '%s' accepted but updating command failed. SubError: %s.",
    "DB-ER1007": "DB-ER1007 - Deposit offer '%s' accepted but updating offer faild. Offer state is '%s', Offer trade ID is '%s'. SubError: %s.",
    "DB-ER1008": "DB-ER1008 - Updating command failed for deposit bad offer '%s'. SubError: %s.",
    "DB-ER1009": "DB-ER1009 - Tracking bad deposit offer '%s' failed. SubError: %s.",
    "DB-ER1010": "DB-ER1010 - Updating command for deposit '%s' offer number '%s' failed. SubError: %s.",
    "DB-ER1011": "DB-ER1011 - Updating offer for deposit '%s' offer number '%s' failed. SubError: %s.",
    "DB-ER1012": "DB-ER1012 - Updating command for deposit '%s' offer number '%s' failed. SubError: %s.",
    "DB-ER1013": "DB-ER1011 - Updating offer for deposit '%s' offer number '%s' failed. SubError: %s.",
    "DB-ER1014": "DB-ER1014 - Withdrawal offer '%s' accepted but updating command failed. SubError: %s.",
    "DB-ER1015": "DB-ER1015 - Withdrawal offer '%s' accepted but updating offer items state failed. SubError: %s.",
    "DB-ER1016": "DB-ER1016 - Withdrawal offer '%s' accepted but updating offer failed. SubError: %s.",
    "DB-ER1017": "DB-ER1017 - Updating command for withdrawal '%s' offer number '%s' failed. SubError: %s.",
    "DB-ER1018": "DB-ER1018 - Updating offer for withdrawal '%s' offer number '%s' failed. SubError: %s.",
    "DB-ER1019": "DB-ER1019 - Unable to revert the items state back to original. SubError: %s.",

    //INFO
    "LOG1001": "LOG1001 - Deposit offer '%s' accepted successfully.",
    "LOG1002": "LOG1002 - Withdrawal offer '%s' accepted successfully.",
    "LOG1003": "LOG1003 - Deposit offer '%s' sent successfully.",
    "LOG1004": "LOG1004 - Withdrawal offer '%s' sent successfully (confirmation awaiting).",
    "LOG1005": "LOG1005 - Withdrawal offer '%s' sent successfully."
};
